export const playersApiMockedData = [
  {
    score: 62.4,
    personId: 203507,
    lastName: 'Antetokounmpo',
    firstName: 'Giannis',
    fullName: 'Giannis Antetokounmpo',
    playerSlug: 'giannis-antetokounmpo',
    teamId: 1610612749,
    teamSlug: 'bucks',
    isDefunct: 0,
    teamCity: 'Milwaukee',
    teamName: 'Bucks',
    teamAbbreviation: 'MIL',
    jerseyNumber: '34',
    position: 'F',
    height: '7-0',
    weight: '243',
    college: 'Filathlitikos',
    country: 'Greece',
    draftYear: 2013,
    draftRound: 1,
    draftNumber: 15,
    rosterStatus: 1,
    points: 29.9,
    rebounds: 11.8,
    assists: 5.5,
    statusTimeframe: 'Season',
    firstYear: '2013',
    lastYear: '2022',
    isActive: true,
    imageLinks: {
      small: 'https://cdn.nba.com/headshots/nba/latest/260x190/203507.png',
      large: 'https://cdn.nba.com/headshots/nba/latest/1040x760/203507.png',
    },
  },
  {
    score: 58.5,
    personId: 201939,
    lastName: 'Curry',
    firstName: 'Stephen',
    fullName: 'Stephen Curry',
    playerSlug: 'stephen-curry',
    teamId: 1610612744,
    teamSlug: 'warriors',
    isDefunct: 0,
    teamCity: 'Golden State',
    teamName: 'Warriors',
    teamAbbreviation: 'GSW',
    jerseyNumber: '30',
    position: 'G',
    height: '6-2',
    weight: '185',
    college: 'Davidson',
    country: 'USA',
    draftYear: 2009,
    draftRound: 1,
    draftNumber: 7,
    rosterStatus: 1,
    points: 31.5,
    rebounds: 6.6,
    assists: 6.4,
    statusTimeframe: 'Season',
    firstYear: '2009',
    lastYear: '2022',
    isActive: true,
    imageLinks: {
      small: 'https://cdn.nba.com/headshots/nba/latest/260x190/201939.png',
      large: 'https://cdn.nba.com/headshots/nba/latest/1040x760/201939.png',
    },
  },
  {
    score: 55,
    personId: 203076,
    lastName: 'Davis',
    firstName: 'Anthony',
    fullName: 'Anthony Davis',
    playerSlug: 'anthony-davis',
    teamId: 1610612747,
    teamSlug: 'lakers',
    isDefunct: 0,
    teamCity: 'Los Angeles',
    teamName: 'Lakers',
    teamAbbreviation: 'LAL',
    jerseyNumber: '3',
    position: 'F-C',
    height: '6-10',
    weight: '253',
    college: 'Kentucky',
    country: 'USA',
    draftYear: 2012,
    draftRound: 1,
    draftNumber: 1,
    rosterStatus: 1,
    points: 24.3,
    rebounds: 11.2,
    assists: 2.5,
    statusTimeframe: 'Season',
    firstYear: '2012',
    lastYear: '2022',
    isActive: true,
    imageLinks: {
      small: 'https://cdn.nba.com/headshots/nba/latest/260x190/203076.png',
      large: 'https://cdn.nba.com/headshots/nba/latest/1040x760/203076.png',
    },
  },
  {
    score: 69.3,
    personId: 1629029,
    lastName: 'Doncic',
    firstName: 'Luka',
    fullName: 'Luka Doncic',
    playerSlug: 'luka-doncic',
    teamId: 1610612742,
    teamSlug: 'mavericks',
    isDefunct: 0,
    teamCity: 'Dallas',
    teamName: 'Mavericks',
    teamAbbreviation: 'DAL',
    jerseyNumber: '77',
    position: 'F-G',
    height: '6-7',
    weight: '230',
    college: 'Real Madrid',
    country: 'Slovenia',
    draftYear: 2018,
    draftRound: 1,
    draftNumber: 3,
    rosterStatus: 1,
    points: 34.4,
    rebounds: 8.8,
    assists: 7.8,
    statusTimeframe: 'Season',
    firstYear: '2018',
    lastYear: '2022',
    isActive: true,
    imageLinks: {
      small: 'https://cdn.nba.com/headshots/nba/latest/260x190/1629029.png',
      large: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1629029.png',
    },
  },
  {
    score: 58,
    personId: 201142,
    lastName: 'Durant',
    firstName: 'Kevin',
    fullName: 'Kevin Durant',
    playerSlug: 'kevin-durant',
    teamId: 1610612751,
    teamSlug: 'nets',
    isDefunct: 0,
    teamCity: 'Brooklyn',
    teamName: 'Nets',
    teamAbbreviation: 'BKN',
    jerseyNumber: '7',
    position: 'F',
    height: '6-10',
    weight: '240',
    college: 'Texas',
    country: 'USA',
    draftYear: 2007,
    draftRound: 1,
    draftNumber: 2,
    rosterStatus: 1,
    points: 30.3,
    rebounds: 6.5,
    assists: 5.3,
    statusTimeframe: 'Season',
    firstYear: '2007',
    lastYear: '2022',
    isActive: true,
    imageLinks: {
      small: 'https://cdn.nba.com/headshots/nba/latest/260x190/201142.png',
      large: 'https://cdn.nba.com/headshots/nba/latest/1040x760/201142.png',
    },
  },
  {
    score: 61.6,
    personId: 203954,
    lastName: 'Embiid',
    firstName: 'Joel',
    fullName: 'Joel Embiid',
    playerSlug: 'joel-embiid',
    teamId: 1610612755,
    teamSlug: 'sixers',
    isDefunct: 0,
    teamCity: 'Philadelphia',
    teamName: '76ers',
    teamAbbreviation: 'PHI',
    jerseyNumber: '21',
    position: 'C-F',
    height: '7-0',
    weight: '280',
    college: 'Kansas',
    country: 'Cameroon',
    draftYear: 2014,
    draftRound: 1,
    draftNumber: 3,
    rosterStatus: 1,
    points: 32.3,
    rebounds: 10.1,
    assists: 4.1,
    statusTimeframe: 'Season',
    firstYear: '2014',
    lastYear: '2022',
    isActive: true,
    imageLinks: {
      small: 'https://cdn.nba.com/headshots/nba/latest/260x190/203954.png',
      large: 'https://cdn.nba.com/headshots/nba/latest/1040x760/203954.png',
    },
  },
  {
    score: 55.4,
    personId: 1628983,
    lastName: 'Gilgeous-Alexander',
    firstName: 'Shai',
    fullName: 'Shai Gilgeous-Alexander',
    playerSlug: 'shai-gilgeous-alexander',
    teamId: 1610612760,
    teamSlug: 'thunder',
    isDefunct: 0,
    teamCity: 'Oklahoma City',
    teamName: 'Thunder',
    teamAbbreviation: 'OKC',
    jerseyNumber: '2',
    position: 'G',
    height: '6-6',
    weight: '195',
    college: 'Kentucky',
    country: 'Canada',
    draftYear: 2018,
    draftRound: 1,
    draftNumber: 11,
    rosterStatus: 1,
    points: 32.3,
    rebounds: 4.5,
    assists: 5.9,
    statusTimeframe: 'Season',
    firstYear: '2018',
    lastYear: '2022',
    isActive: true,
    imageLinks: {
      small: 'https://cdn.nba.com/headshots/nba/latest/260x190/1628983.png',
      large: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1628983.png',
    },
  },
  {
    score: 58.8,
    personId: 201935,
    lastName: 'Harden',
    firstName: 'James',
    fullName: 'James Harden',
    playerSlug: 'james-harden',
    teamId: 1610612755,
    teamSlug: 'sixers',
    isDefunct: 0,
    teamCity: 'Philadelphia',
    teamName: '76ers',
    teamAbbreviation: 'PHI',
    jerseyNumber: '1',
    position: 'G',
    height: '6-5',
    weight: '220',
    college: 'Arizona State',
    country: 'USA',
    draftYear: 2009,
    draftRound: 1,
    draftNumber: 3,
    rosterStatus: 1,
    points: 22,
    rebounds: 7,
    assists: 10,
    statusTimeframe: 'Season',
    firstYear: '2009',
    lastYear: '2022',
    isActive: true,
    imageLinks: {
      small: 'https://cdn.nba.com/headshots/nba/latest/260x190/201935.png',
      large: 'https://cdn.nba.com/headshots/nba/latest/1040x760/201935.png',
    },
  },
  {
    score: 61,
    personId: 2544,
    lastName: 'James',
    firstName: 'LeBron',
    fullName: 'LeBron James',
    playerSlug: 'lebron-james',
    teamId: 1610612747,
    teamSlug: 'lakers',
    isDefunct: 0,
    teamCity: 'Los Angeles',
    teamName: 'Lakers',
    teamAbbreviation: 'LAL',
    jerseyNumber: '6',
    position: 'F',
    height: '6-9',
    weight: '250',
    college: 'St. Vincent-St. Mary HS (OH)',
    country: 'USA',
    draftYear: 2003,
    draftRound: 1,
    draftNumber: 1,
    rosterStatus: 1,
    points: 24.9,
    rebounds: 8.8,
    assists: 6.9,
    statusTimeframe: 'Season',
    firstYear: '2003',
    lastYear: '2022',
    isActive: true,
    imageLinks: {
      small: 'https://cdn.nba.com/headshots/nba/latest/260x190/2544.png',
      large: 'https://cdn.nba.com/headshots/nba/latest/1040x760/2544.png',
    },
  },
  {
    score: 59.6,
    personId: 1629630,
    lastName: 'Morant',
    firstName: 'Ja',
    fullName: 'Ja Morant',
    playerSlug: 'ja-morant',
    teamId: 1610612763,
    teamSlug: 'grizzlies',
    isDefunct: 0,
    teamCity: 'Memphis',
    teamName: 'Grizzlies',
    teamAbbreviation: 'MEM',
    jerseyNumber: '12',
    position: 'G',
    height: '6-2',
    weight: '174',
    college: 'Murray State',
    country: 'USA',
    draftYear: 2019,
    draftRound: 1,
    draftNumber: 2,
    rosterStatus: 1,
    points: 29.3,
    rebounds: 6.2,
    assists: 6.8,
    statusTimeframe: 'Season',
    firstYear: '2019',
    lastYear: '2022',
    isActive: true,
    imageLinks: {
      small: 'https://cdn.nba.com/headshots/nba/latest/260x190/1629630.png',
      large: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1629630.png',
    },
  },
  {
    score: 58.2,
    personId: 1627783,
    lastName: 'Siakam',
    firstName: 'Pascal',
    fullName: 'Pascal Siakam',
    playerSlug: 'pascal-siakam',
    teamId: 1610612761,
    teamSlug: 'raptors',
    isDefunct: 0,
    teamCity: 'Toronto',
    teamName: 'Raptors',
    teamAbbreviation: 'TOR',
    jerseyNumber: '43',
    position: 'F',
    height: '6-8',
    weight: '230',
    college: 'New Mexico State',
    country: 'Cameroon',
    draftYear: 2016,
    draftRound: 1,
    draftNumber: 27,
    rosterStatus: 1,
    points: 24.8,
    rebounds: 9.3,
    assists: 7.7,
    statusTimeframe: 'Season',
    firstYear: '2016',
    lastYear: '2022',
    isActive: true,
    imageLinks: {
      small: 'https://cdn.nba.com/headshots/nba/latest/260x190/1627783.png',
      large: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1627783.png',
    },
  },
  {
    score: 56.7,
    personId: 1628369,
    lastName: 'Tatum',
    firstName: 'Jayson',
    fullName: 'Jayson Tatum',
    playerSlug: 'jayson-tatum',
    teamId: 1610612738,
    teamSlug: 'celtics',
    isDefunct: 0,
    teamCity: 'Boston',
    teamName: 'Celtics',
    teamAbbreviation: 'BOS',
    jerseyNumber: '0',
    position: 'F-G',
    height: '6-8',
    weight: '210',
    college: 'Duke',
    country: 'USA',
    draftYear: 2017,
    draftRound: 1,
    draftNumber: 3,
    rosterStatus: 1,
    points: 31.1,
    rebounds: 7.4,
    assists: 4.1,
    statusTimeframe: 'Season',
    firstYear: '2017',
    lastYear: '2022',
    isActive: true,
    imageLinks: {
      small: 'https://cdn.nba.com/headshots/nba/latest/260x190/1628369.png',
      large: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1628369.png',
    },
  },
  {
    score: 55.1,
    personId: 1629027,
    lastName: 'Young',
    firstName: 'Trae',
    fullName: 'Trae Young',
    playerSlug: 'trae-young',
    teamId: 1610612737,
    teamSlug: 'hawks',
    isDefunct: 0,
    teamCity: 'Atlanta',
    teamName: 'Hawks',
    teamAbbreviation: 'ATL',
    jerseyNumber: '11',
    position: 'G',
    height: '6-1',
    weight: '164',
    college: 'Oklahoma',
    country: 'USA',
    draftYear: 2018,
    draftRound: 1,
    draftNumber: 5,
    rosterStatus: 1,
    points: 26.9,
    rebounds: 3.3,
    assists: 9.3,
    statusTimeframe: 'Season',
    firstYear: '2018',
    lastYear: '2022',
    isActive: true,
    imageLinks: {
      small: 'https://cdn.nba.com/headshots/nba/latest/260x190/1629027.png',
      large: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1629027.png',
    },
  },
]
